name: ICT3104
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - ipykernel = 6.15.3
  - pip:
    - joblib==1.1.0
    - numpy==1.23.3
    - pillow==9.2.0
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - torch==1.10.1
    - torchaudio==0.10.1
    - torchvision==0.11.2
    - tqdm==4.64.1